### PR TITLE
Added composer scripts.

### PR DESCRIPTION
**Pull request by thom8**
Adding some composer scripts with robo support.

Run `composer run-script --list` for full list.

`composer deploy` runs ansible playbook.
`composer test` for phpcs & behat.

### CODE REVIEW

**Comment by thom8** [comment]
Set up could be just `git clone ... composer up`

**Comment by geerlingguy** [comment]
Nice.

Will test and merge later (hopefully today!).

**Comment by thom8** [comment]
Feel free to push back on anything that doesn't make sense for this project.

**Comment by thom8** [comment]
Closing out old PRs.

**Pull request closed without merging**
